#!/usr/bin/env bash
# validate-distribution-shape.sh — Numerical-correctness harness for ltl's
# distribution-shape statistics (Issue #254).
#
# Validates skewness / kurtosis / bimodality_coef in the MESSAGES CSV
# against synthetic input distributions with known analytic shape. This is
# the *numerical* counterpart to the structural CSV harness (#223) and the
# absolute-correctness counterpart to the drift/oracle harness (#224): #224
# checks that ltl agrees with SciPy on real logs (catching drift), whereas
# this harness checks that ltl's values match distribution theory on inputs
# whose shape is known a priori (catching a bug where ltl and the oracle
# would compute the same wrong thing, and anchoring the BC 0.555 threshold).
#
# Each anchor is a synthetic Tomcat access log generated by
# tests/distribution-shape/generate-anchor.py (seeded; byte-identical per
# run). All lines share one URL, so ltl collapses the samples into a single
# MESSAGES-CSV row whose shape columns characterize the whole distribution.
# Tolerance bands are fixed (Issue #254 anchor table); the fixed RNG seed is
# what makes fixed bands legitimate.
#
# Scope (per #254): raw-array data model only (the default per-message-key
# surface). Shape stats under the bin-counter data model are a separate
# concern. Percentile columns (p25, iqr, p9999) are out of scope here —
# they are validated numerically by #224.
#
# The exponential anchor asserts skewness and kurtosis only: a true
# exponential's bimodality coefficient sits right on Sarle's 0.555 cutoff
# (the cutoff is near the BC of high-skew distributions), so a BC assertion
# there would be testing a value on the threshold. The unimodal-side BC
# evidence comes from the normal anchor (BC well below 0.555); the bimodal
# anchor supplies BC well above 0.555. Normal and bimodal bracket the
# threshold cleanly.
#
# Usage:
#   ./tests/validate-distribution-shape.sh                 # all anchors
#   ./tests/validate-distribution-shape.sh --anchor normal # single anchor
#
# Exit codes:
#   0  all assertions passed
#   1  at least one assertion failed, or a missing anchor / non-numeric value
#   2  usage error
#
# Requires python3 + numpy (the generator). Fails fast with an install hint
# if numpy is missing — it does NOT silently skip (that would be a false pass).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LTL="$REPO_DIR/ltl"
GENERATOR="$SCRIPT_DIR/distribution-shape/generate-anchor.py"

ONLY_ANCHOR=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --anchor) ONLY_ANCHOR="$2"; shift 2 ;;
        -h|--help) sed -n '2,46p' "$0"; exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

for f in "$LTL" "$GENERATOR"; do
    if [[ ! -e "$f" ]]; then
        echo "ERROR: required file missing: $f" >&2
        exit 1
    fi
done
if [[ ! -x "$LTL" ]]; then
    echo "ERROR: ltl not executable: $LTL" >&2
    exit 1
fi

# Generator dependency preflight. Fail fast — never silently skip.
if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: this harness requires python3 (not found on PATH)." >&2
    echo "       macOS:  brew install python" >&2
    echo "       Ubuntu: sudo apt-get install python3" >&2
    exit 1
fi
if ! python3 -c 'import numpy' >/dev/null 2>&1; then
    echo "ERROR: the anchor generator requires numpy (not importable)." >&2
    echo "       macOS:  pip3 install numpy" >&2
    echo "       Ubuntu: sudo apt-get install python3-numpy" >&2
    exit 1
fi

# All transient artifacts live under one temp root, cleaned unconditionally.
TMP_ROOT=$(mktemp -d); trap 'rm -rf "$TMP_ROOT"' EXIT

pass=0
fail=0
failures=()
current_anchor=""

# Generate one anchor log, run ltl -o on it in its own dir (the CSV filename
# carries a wall-clock timestamp to the second, so anchors run in the same
# second would otherwise collide), and echo the path to the MESSAGES CSV.
# Hard-fails (exit 1) on any breakdown in the chain so a broken setup can
# never present as a passing assertion (HARNESS-DESIGN.md traps 1, 3, 7).
generate_and_run() {
    local anchor="$1"
    local logfile="$TMP_ROOT/$anchor.log"
    local rundir="$TMP_ROOT/$anchor.run"
    mkdir -p "$rundir"

    if ! python3 "$GENERATOR" "$anchor" "$logfile" 2>"$TMP_ROOT/$anchor.gen.err"; then
        echo "ERROR: anchor generation failed for '$anchor':" >&2
        sed 's/^/    /' "$TMP_ROOT/$anchor.gen.err" >&2
        exit 1
    fi
    if [[ ! -s "$logfile" ]]; then
        echo "ERROR: generated log is empty: $logfile" >&2
        exit 1
    fi

    if ! ( cd "$rundir" && "$LTL" --disable-progress -o "$logfile" \
           >/dev/null 2>"$TMP_ROOT/$anchor.ltl.err" ); then
        echo "ERROR: ltl failed for anchor '$anchor':" >&2
        sed 's/^/    /' "$TMP_ROOT/$anchor.ltl.err" >&2
        exit 1
    fi

    local csv
    csv=$(find "$rundir" -name '*MESSAGES*.csv' -type f | head -1)
    if [[ -z "$csv" || ! -s "$csv" ]]; then
        echo "ERROR: no MESSAGES CSV produced for anchor '$anchor' in $rundir" >&2
        exit 1
    fi
    echo "$csv"
}

# Self-documenting numeric-band assertion. Extracts one column from the
# single data row of a MESSAGES CSV and asserts lo <= value <= hi.
#
# Required named fields:
#   csv column lo hi   — the artifact, column name, and inclusive band
#   asserts            — the application invariant being tested
#   produced_by        — where in ltl the value is produced (function name)
#   contract           — the stability source the reader judges against
#
# Missing CSV column, missing/extra data row, or a non-numeric value are
# hard failures surfaced with all four documentation fields, never silent.
assert_in_band() {
    local csv="" column="" lo="" hi="" asserts="" produced_by="" contract=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            csv)         csv="$2";         shift 2 ;;
            column)      column="$2";      shift 2 ;;
            lo)          lo="$2";          shift 2 ;;
            hi)          hi="$2";          shift 2 ;;
            asserts)     asserts="$2";     shift 2 ;;
            produced_by) produced_by="$2"; shift 2 ;;
            contract)    contract="$2";    shift 2 ;;
            *) echo "assert_in_band: unknown field '$1'" >&2; exit 2 ;;
        esac
    done
    : "${csv:?assert_in_band requires csv}"
    : "${column:?assert_in_band requires column}"
    : "${lo:?assert_in_band requires lo}"
    : "${hi:?assert_in_band requires hi}"
    : "${asserts:?assert_in_band requires asserts}"
    : "${produced_by:?assert_in_band requires produced_by}"
    : "${contract:?assert_in_band requires contract}"

    # Extract the value with a real CSV parser (never naive split — the
    # message column contains commas). Python prints the value on success,
    # or an ERROR: line to stderr and exits non-zero on any structural
    # problem (missing column, wrong row count, non-numeric).
    local value
    if ! value=$(python3 - "$csv" "$column" <<'PY'
import csv, sys
path, col = sys.argv[1], sys.argv[2]
with open(path, newline="") as fh:
    rows = list(csv.DictReader(fh))
if len(rows) != 1:
    sys.stderr.write(f"ERROR: expected exactly 1 data row, got {len(rows)}\n")
    sys.exit(1)
row = rows[0]
if col not in row:
    sys.stderr.write(f"ERROR: column '{col}' not present in CSV header\n")
    sys.exit(1)
raw = row[col]
try:
    v = float(raw)
except (TypeError, ValueError):
    sys.stderr.write(f"ERROR: column '{col}' value {raw!r} is not numeric\n")
    sys.exit(1)
print(repr(v))
PY
    ); then
        echo "  FAIL  $current_anchor :: $column"
        echo "        extraction:  $value"
        echo "        asserts:     $asserts"
        echo "        produced_by: $produced_by"
        echo "        contract:    $contract"
        echo "        (CSV: $csv)"
        fail=$((fail + 1))
        failures+=("$current_anchor :: $column (extraction failed)")
        return
    fi

    # In-band comparison in python (float-safe inclusive bounds).
    if python3 -c "import sys; v=$value; sys.exit(0 if $lo <= v <= $hi else 1)"; then
        echo "  PASS  $current_anchor :: $column = $value in [$lo, $hi]"
        pass=$((pass + 1))
    else
        echo "  FAIL  $current_anchor :: $column"
        echo "        value:       $value"
        echo "        band:        [$lo, $hi]"
        echo "        asserts:     $asserts"
        echo "        produced_by: $produced_by"
        echo "        contract:    $contract"
        echo "        (CSV: $csv)"
        fail=$((fail + 1))
        failures+=("$current_anchor :: $column=$value not in [$lo, $hi]")
    fi
}

# Bands and produced_by/contract are shared across anchors.
PRODUCED_BY='calculate_statistics() in ltl (raw-array data model: sample-corrected standardized 3rd/4th central moments, Sarle BC = (skew^2+1)/(kurtosis + 3(n-1)^2/((n-2)(n-3))))'
CONTRACT='Issue #254 anchor table + features/222-* (shape moments). Bands fixed against analytic distribution values; the generator seed makes the sample deterministic, so a band failure is a real numerical regression in the moment computation, not sampling noise.'

# ---------------------------------------------------------------------------
# normal — N(100, 10), n=10000 : symmetric, mesokurtic, unimodal
# ---------------------------------------------------------------------------
anchor_normal() {
    current_anchor="normal"
    echo "[$current_anchor]"
    local csv; csv=$(generate_and_run normal)

    assert_in_band csv "$csv" column skewness lo -0.1 hi 0.1 \
        asserts     'A normal (symmetric) distribution has skewness ~0; ltl must report near-zero skewness for N(100,10)' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"

    assert_in_band csv "$csv" column kurtosis lo -0.2 hi 0.2 \
        asserts     'A normal distribution has excess kurtosis ~0; ltl uses the Fisher (excess) convention so normal must read near zero' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"

    assert_in_band csv "$csv" column bimodality_coef lo 0 hi 0.5549999 \
        asserts     'A unimodal distribution has bimodality_coef below the 0.555 (5/9) Sarle cutoff; ltl must not flag normal as multimodal' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"
}

# ---------------------------------------------------------------------------
# exponential — Exp(1)*100, n=200000 : right-skewed, heavy-tailed, unimodal
# n is large so the 3rd/4th sample moments tighten onto the analytic values.
# BC is intentionally not asserted (sits on the 0.555 cutoff — see header).
# ---------------------------------------------------------------------------
anchor_exponential() {
    current_anchor="exponential"
    echo "[$current_anchor]"
    local csv; csv=$(generate_and_run exponential)

    assert_in_band csv "$csv" column skewness lo 1.8 hi 2.2 \
        asserts     'An exponential distribution has skewness 2.0 (analytic); ltl must report ~2.0 for Exp(1)' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"

    assert_in_band csv "$csv" column kurtosis lo 5.0 hi 7.0 \
        asserts     'An exponential distribution has excess kurtosis 6.0 (analytic); ltl must report ~6.0 for Exp(1)' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"
}

# ---------------------------------------------------------------------------
# bimodal — N(50,5) + N(500,50), 1000 each : two well-separated modes
# skew/kurtosis bands are pinned from the seeded sample (stable across seeds
# to ~0.01); the operationally meaningful assertion is BC above 0.555.
# ---------------------------------------------------------------------------
anchor_bimodal() {
    current_anchor="bimodal"
    echo "[$current_anchor]"
    local csv; csv=$(generate_and_run bimodal)

    assert_in_band csv "$csv" column bimodality_coef lo 0.5550001 hi 1.0 \
        asserts     'A clearly bimodal distribution (two separated modes) has bimodality_coef above the 0.555 Sarle cutoff; ltl must flag it as suspect multimodal' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"

    assert_in_band csv "$csv" column skewness lo 0.028 hi 0.128 \
        asserts     'The two equal-mass, separated modes are near-symmetric about the grand mean, giving small positive skewness; pinned from the seeded sample' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"

    assert_in_band csv "$csv" column kurtosis lo -1.994 hi -1.794 \
        asserts     'Two separated equal-mass modes produce strongly platykurtic (negative excess kurtosis) shape; pinned from the seeded sample' \
        produced_by "$PRODUCED_BY" contract "$CONTRACT"
}

# ---------------------------------------------------------------------------
run_anchor() {
    case "$1" in
        normal)      anchor_normal ;;
        exponential) anchor_exponential ;;
        bimodal)     anchor_bimodal ;;
        *) echo "unknown anchor: $1" >&2; exit 2 ;;
    esac
}

if [[ -n "$ONLY_ANCHOR" ]]; then
    run_anchor "$ONLY_ANCHOR"
else
    anchor_normal; echo ""
    anchor_exponential; echo ""
    anchor_bimodal
fi

echo ""
echo "Results: $pass passed, $fail failed"
if [[ "$fail" -gt 0 ]]; then
    echo "Failures:"
    for f in "${failures[@]}"; do
        echo "  - $f"
    done
    exit 1
fi
echo "ALL DISTRIBUTION-SHAPE TESTS PASSED"
